### ISSUE TITLE
User setting for single-line groupings

### ISSUE THREAD

**Issue by gavinr** [agrc/atom-amdbutler#35]
Would love similar functionality to https://github.com/agrc/AmdButler/issues/19 ... do you know if that code could be ported over? Thanks!

**Comment by stdavis** [comment]
Yes, I'm sure that could be ported to the Atom version.

We'd just need to add a new setting [here](https://github.com/agrc/atom-amdbutler/blob/master/lib/atom-amdbutler.js#L11) called `oneLine` or something.

Then check for that setting [here](https://github.com/agrc/atom-amdbutler/blob/master/lib/zipper.js#L39) & [here](https://github.com/agrc/atom-amdbutler/blob/master/lib/zipper.js#L64) and apply the appropriate formatting..

I don't know if this would ever be high on the priority list for us because we don't use that format, but PR's are definitely welcome.

**Comment by gavinr** [comment]
Thanks @stdavis. Will look at getting together a PR.

**Comment by stdavis** [comment]
Blast from the past!

**Comment by gavinr** [comment]
Lol! Just cleaning up some outdated stuff this morning :)
